import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuaryClient from "@/provider/QuaryClient";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  applicationName: "readme.MD",
  title: "readme.MD",
  description: "Generated by readme.MD",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QuaryClient >
          <Toaster position="top-right"
            reverseOrder={false} />
          <div className="w-full">
            {children}
          </div>
        </QuaryClient>
      </body>
    </html>
  );
}
